/*
 * DepartmentsPanel.java
 *
 * Created on April 3, 2008, 4:38 PM
 */

package com.md.invapp;

import com.md.invapp.data.entities.InvAppEntitiy;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.Vector;

import stdClasses.StatusBar;

/**
 *
 * @author  nla
 */
public class ItemSalesPanel extends InvAppMaintPanel {
    
    /**
     * Creates a new instance of ItemPanel
     *
     * @param transObectRecord
     * @param itemRecord
     * @param headerInterface
     * @param salesTransInterface
     * @param runtimeArgs
     */

    public ItemSalesPanel(ItemTransObjectRecord transObectRecord, ItemRecord itemRecord, 
            ItemSalesHeaderInterface headerInterface, ItemSalesTransInterface salesTransInterface, RuntimeArgs runtimeArgs) {

        initComponents();
        
        this.transObectRecord = transObectRecord;
        headerPanel = new ItemSalesHeaderPanel(transObectRecord.getHeaderRecord(), headerInterface);
        transPanel = new ItemSalesTransPanel(itemRecord, salesTransInterface);
        footerPanel = new ItemSalesFooterPanel(transObectRecord.getHeaderRecord());
        
        initPanels();
    }
    
    private void initPanels() {
        setLayout(new BorderLayout());        
        
        add(headerPanel,BorderLayout.NORTH);
        add(transPanel,BorderLayout.CENTER);
        add(footerPanel,BorderLayout.SOUTH);        
        
        transPanel.addSalesFooterInterface(footerPanel);
        transPanel.addSalesHeaderInterface(headerPanel);        
        
        setPreferredSize(new Dimension(1000, 520));
        repaint();
        
        setEditable(false);
        transPanel.setButtonEnabled(false);
    }
        
    public void addSalesMainFrameInterface(ItemSalesMainFrameInterface salesFrameInterface) {
        transPanel.addSalesMainFrameInterface(salesFrameInterface);
    }

    public void initScanPanel(Vector<Vector> listDet) {
        clearForm();
    }
    
    public void initNewTrans() {        
        headerPanel.initNewTrans();        
    }

    public void additemSalesFooterListener() {
        
    }

    public void addItemCodeSanListener(ItemScanListener itemsScanListener) {
        transPanel.addItemCodeSanListener(itemsScanListener);
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Sales Tansaction"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Sales Transaction");
    }// </editor-fold>//GEN-END:initComponents

    
    @Override
    public void populatedEntity(InvAppEntitiy invAppEntity) {        
    }

    
    public void fillRecord() {        
        headerPanel.fillRecord();
        footerPanel.fillRecord();
        transObectRecord.setTransactions(transPanel.getItemTransactions());
    }
    
    @Override
    public void clearForm() {
        headerPanel.clearForm();
        transPanel.clearForm();
        footerPanel.clearForm();
    }
    
    @Override
    public void setEditable(boolean editRec) {
        headerPanel.setEditable(editRec);
        transPanel.setEditable(editRec, true);
        footerPanel.setEditable(editRec);
    }

    public void setHeaderFooterEditable(boolean editRec) {
        headerPanel.setEditable(editRec);
        footerPanel.setEditable(editRec);
    }
    
    public void setTransPanelEditable(boolean editRec) {
        transPanel.setEditable(editRec, true);
    }
    
    public boolean entriesComplete() {        
        return headerPanel.entriesComplete() && 
                transPanel.entriesComplete() && 
                footerPanel.entriesComplete();
    }

    @Override
    public void setStatusBar(StatusBar statusBar) {        
    }
    
    @Override
    public void setEnableSearchList(boolean mode) {
    }


    private final ItemTransObjectRecord transObectRecord;
    private final ItemSalesHeaderPanel headerPanel;
    private final ItemSalesTransPanel transPanel;
    private final ItemSalesFooterPanel footerPanel;
    
    public static final int ITEM_TABLE = 0;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
    
}
